/*
 * Copyright (c) 2025, GigaDevice Semiconductor Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_GD32C2X1_CLOCKS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_GD32C2X1_CLOCKS_H_

#include "gd32-clocks-common.h"

/**
 * @name Register offsets
 * @{
 */

#define GD32_AHB1EN_OFFSET       0x30U
#define GD32_AHB2EN_OFFSET       0x34U
#define GD32_APBEN_OFFSET        0x44U

/** @} */

/**
 * @name Clock enable/disable definitions for peripherals
 * @{
 */
/* AHB1 peripherals */
#define GD32_CLOCK_FMC        GD32_CLOCK_CONFIG(AHB1EN, 4U)
#define GD32_CLOCK_CRC        GD32_CLOCK_CONFIG(AHB1EN, 12U)
#define GD32_CLOCK_DMA        GD32_CLOCK_CONFIG(AHB1EN, 21U)
#define GD32_CLOCK_GPIOF      GD32_CLOCK_CONFIG(AHB1EN, 23U)

/* AHB2 peripherals */
#define GD32_CLOCK_GPIOA      GD32_CLOCK_CONFIG(AHB2EN, 17U)
#define GD32_CLOCK_GPIOB      GD32_CLOCK_CONFIG(AHB2EN, 18U)
#define GD32_CLOCK_GPIOC      GD32_CLOCK_CONFIG(AHB2EN, 19U)
#define GD32_CLOCK_GPIOD      GD32_CLOCK_CONFIG(AHB2EN, 20U)

/* APB peripherals */
#define GD32_CLOCK_SYSCFG     GD32_CLOCK_CONFIG(APBEN, 0U)
#define GD32_CLOCK_CMP        GD32_CLOCK_CONFIG(APBEN, 1U)
#define GD32_CLOCK_WWDGT      GD32_CLOCK_CONFIG(APBEN, 8U)
#define GD32_CLOCK_ADC        GD32_CLOCK_CONFIG(APBEN, 9U)
#define GD32_CLOCK_TIMER0     GD32_CLOCK_CONFIG(APBEN, 10U)
#define GD32_CLOCK_TIMER2     GD32_CLOCK_CONFIG(APBEN, 11U)
#define GD32_CLOCK_SPI0       GD32_CLOCK_CONFIG(APBEN, 12U)
#define GD32_CLOCK_SPI1       GD32_CLOCK_CONFIG(APBEN, 13U)
#define GD32_CLOCK_USART0     GD32_CLOCK_CONFIG(APBEN, 14U)
#define GD32_CLOCK_USART1     GD32_CLOCK_CONFIG(APBEN, 15U)
#define GD32_CLOCK_TIMER13    GD32_CLOCK_CONFIG(APBEN, 16U)
#define GD32_CLOCK_TIMER15    GD32_CLOCK_CONFIG(APBEN, 17U)
#define GD32_CLOCK_TIMER16    GD32_CLOCK_CONFIG(APBEN, 18U)
#define GD32_CLOCK_USART2     GD32_CLOCK_CONFIG(APBEN, 19U)
#define GD32_CLOCK_I2C0       GD32_CLOCK_CONFIG(APBEN, 21U)
#define GD32_CLOCK_I2C1       GD32_CLOCK_CONFIG(APBEN, 22U)
#define GD32_CLOCK_DBG        GD32_CLOCK_CONFIG(APBEN, 27U)
#define GD32_CLOCK_PMU        GD32_CLOCK_CONFIG(APBEN, 28U)

/** @} */

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_GD32C2X1_CLOCKS_H_ */
